### ISSUE TITLE
cannot open shared object file: no such file or directory

### ISSUE THREAD

**Issue by 21212124** [google/AFL#58]
Hi,

I have this error, but I don't understand why. 
![AFL](https://user-images.githubusercontent.com/30496643/70515539-c923ba80-1b35-11ea-86f9-2b1837582d5a.PNG)

The file is in the directory, why can't it find it?
![afl_validate](https://user-images.githubusercontent.com/30496643/70515554-cfb23200-1b35-11ea-9998-27442b64a928.PNG)

Any ideas?

Thanks.

**Comment by NapongiZero** [comment]
Since it's a shared object you might want to write a wrapper around it. 
For example, write a simple C program that calls functions from the .SO file and compile it (statically) with the shared object file, and then fuzz the compiled binary.
Also, this error usually shows when there's an issue with the permissions of the file. 

P.S. Please try to google issues before creating an _issue_ on the GitHub repository. It would save you a lot of time, as you would get a faster response. The answer is most likely already there.

**Comment by jonathanmetzman** [comment]
@21212124 I don't really know based on what you've showed me. The screenshot you show is of (Per?)sonal/Escritorio/optee_3_3/afl-tee/out which may not be the same as the one you are using on the command line. Other than that I don't have any guesses. My recommendation would be to try the example in experimental/post_library/post_library_png.c first.
@NapongiZero Really appreciate the help with issues you've been providing.
