### ISSUE TITLE
Status Screen Question: How many edges are covered?

### ISSUE THREAD

**Issue by AIK13** [google/AFL#89]
Hi, 
I want to compare AFL to other fuzzers by number of edges covered, but I don't see that statistic in the status screen. I see cycles done and total paths, but not total edges covered. Is there a way to see how many edges are covered?

**Comment by jonathanmetzman** [comment]
There's bitmap_cvg in fuzzer_stats but note that this is not the same as edge coverage count because AFL's coverage instrumentation can have collisions between different edges in the bitmap. AFL is fundamentally unable to provide this info and if you'd like to compare fuzzers you should probably measure the coverage obtained by both fuzzers using the corpora offline instead of relying on what they say the coverage is.
